In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
df = pd.read_csv("winequality-red.csv", sep=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
print("Shape:", df.shape)
df.info()

Shape: (1599, 12)
<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [10]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [11]:
df.select_dtypes(include="object").columns

Index([], dtype='str')

In [12]:
df["total_acidity"] = (
    df["fixed acidity"] +
    df["volatile acidity"] +
    df["citric acid"]
)

df["sulfur_ratio"] = (
    df["free sulfur dioxide"] /
    (df["total sulfur dioxide"] + 1)
)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,total_acidity,sulfur_ratio
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,8.10,0.314286
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,8.68,0.367647
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,8.60,0.272727
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,12.04,0.278689
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,8.10,0.314286

In [16]:
X = df.drop("quality", axis=1)
y = df["quality"]

In [17]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42
)
print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)

(1119, 13)
(240, 13)
(240, 13)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [19]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [20]:
pred = model.predict(X_valid)

In [21]:
print("MAE:", mean_absolute_error(y_valid, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_valid, pred)))
print("R2:", r2_score(y_valid, pred))

MAE: 0.5162502864449815
RMSE: 0.6358306759339555
R2: 0.3214672527982424

In [22]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge())
])

params = {
    "model__alpha": [0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(
    pipeline,
    params,
    cv=5,
    scoring="neg_mean_squared_error"
)
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Ridge())]),
             param_grid={'model__alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

In [23]:
grid.best_params_

{'model__alpha': 100}

In [24]:
best_model = grid.best_estimator_
pred = best_model.predict(X_test)

In [25]:
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))
print("R2:", r2_score(y_test, pred))

MAE: 0.5103978840911135
RMSE: 0.6460892439193044
R2: 0.3790278016571955

Трохи коду від мене

In [29]:
coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": best_model.named_steps["model"].coef_
})
coef.sort_values("Coefficient", ascending=False)

                 Feature  Coefficient
10               alcohol     0.266001
9              sulphates     0.133054
12          sulfur_ratio     0.051536
0          fixed acidity     0.037008
3         residual sugar     0.018757
11         total_acidity     0.015460
5    free sulfur dioxide    -0.006667
2            citric acid    -0.014596
8                     pH    -0.026986
7                density    -0.050626
6   total sulfur dioxide    -0.058629
4              chlorides    -0.075508
1       volatile acidity    -0.179462

In [30]:
coef["Absolute"] = coef["Coefficient"].abs()
coef.sort_values("Absolute", ascending=False)

                 Feature  Coefficient  Absolute
10               alcohol     0.266001  0.266001
1       volatile acidity    -0.179462  0.179462
9              sulphates     0.133054  0.133054
4              chlorides    -0.075508  0.075508
6   total sulfur dioxide    -0.058629  0.058629
12          sulfur_ratio     0.051536  0.051536
7                density    -0.050626  0.050626
0          fixed acidity     0.037008  0.037008
8                     pH    -0.026986  0.026986
3         residual sugar     0.018757  0.018757
11         total_acidity     0.015460  0.015460
2            citric acid    -0.014596  0.014596
5    free sulfur dioxide    -0.006667  0.006667

In [31]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": pred
})
comparison.head(10)

   Actual  Predicted
0       6   5.883744
1       5   5.807875
2       7   6.060458
3       6   6.141214
4       7   6.113841
5       7   6.257393
6       6   5.915049
7       6   6.244388
8       5   5.856250
9       6   6.413013

In [32]:
error = abs(y_test.values - pred)
print("Average prediction error:", error.mean())

Average prediction error: 0.5103978840911135

Додатково я проаналізовала коефіцієнти моделі та порівняно прогнозовані значення з фактичними, що дозволило краще оцінити точність прогнозування та вплив окремих ознак на результат.